
[package]
name = "solpin"
version = "0.0.1"
description = "Program to pin string to Solana"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9.1"
borsh-derive = "0.9.1"
byteorder = "1.3"
solana-program = "=1.7.11"

[lib]
name = "dapp"
crate-type = ["cdylib", "lib"]

